name: ((deployment_name))
instance_groups:
- name: jenkins-master
  azs: [z1]
  instances: 1
  jobs:
  - name: jenkins-master
    release: devtools
    properties:
      jenkins:
        config: config.xml
        admin:
          email: admin@localhost
          password: ((jenkins_admin_password))
        agent:
          password: ((jenkins_agent_password))
        server:
          address: http://localhost:8080/
        github:
          oauth:
            org_name: ((github_oauth_org_name))
            admins:
              admin1: ((jenkins_oauth_admin_user_1))
              admin2: ((jenkins_oauth_admin_user_2))
              admin3: ((jenkins_oauth_admin_user_3))
            url:
              web: ((jenkins_oauth_github_web_ui))
              api: ((jenkins_oauth_github_api_ui))
            client:
              id: ((jenkins_oauth_clientID))
              secret: ((jenkins_oauth_clientSecret))
  networks:
  - name: default
  persistent_disk_pool: 10GB
  stemcell: default
  vm_type: small
- name: jenkins-slave
  azs: [z1]
  instances: 1
  jobs:
  - name: jenkins-slave
    release: devtools
    properties:
      jenkins:
        slave:
          executors: 2
          labels: build
          master_password: ((jenkins_agent_password))
          master_username: agent
          mode: exclusive
  networks:
  - name: default
  stemcell: default
  vm_type: small

releases:
- name: devtools
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 15000-300000
  max_in_flight: 1
  update_watch_time: 15000-300000

variables:
- name: jenkins_admin_password
  type: password
- name: jenkins_agent_password
  type: password
