name: ((deployment_name))
instance_groups:
- name: sonarqube
  azs: [z1]
  instances: 1
  jobs:
  - name: sonarqube
    properties:
      github:
        server:
          url: http://127.0.0.1/wont_work
      sonar:
        client:
          id: 00000000000000000000
          secret: 0000000000000000000000000000000000000000
    release: devtools
  networks:
  - name: default
  stemcell: default
  vm_type: small

releases:
- name: devtools
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 15000-300000
  max_in_flight: 1
  update_watch_time: 15000-300000